language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- nightly
install:
- pip install .
script:
- py.test tests
deploy:
  provider: pypi
  user: kalekundert
  password:
    secure: ASHskdHS3/ZN+KeCRcyMKKzYv/plwPE3JHOUT49j5qpy8HXKGKAw0zHUDeTsnwsGRkBtZcYWb1FhZf1zBUOh0LtdbMtxzHdpoE4p2B3zWq9DGKNllmsUiIU+GtYnN8LGz5E3IFVIXB7BF7N9el+hEhCundYcMfqvz5OiSwy7j2liinw9uL/oi1047eS0IfbyJooR2vIPXhFzlGMuFRpsEnNewTYW9pkRnrrOv1YFLZWLE1ioj8JbFRd0Li5yF8ER7YLZz9jgxFel5SOGy9Ox2ESzpx1D7Z+AFfMJLK30WFrICPHR9A3cWku3nSYAndJrfvtBkPj2LjFxaW8fP60wTIGIDzi4MnuSGS4+IpfpQ8AHok3y7eC0c8jhvvjcEAeJ8zRW14Gz7GR02BKhyp3WS7J+NsUcwbiza41fF2pPguzjqUkJOH27zETCiIXQmtW6LWbYD+0vDxW0PjHnsnfiG/E0MPTCC6f5gGsWdViqyX541cBVJW/34XGp5EW9IXCts93WJ0f0NyxPMpgTi54fQH1LMfqNgApFfd2tM7Wjh2RkyDd6Gp6evmiAsfYaO1oEPg+nLi/BwGc3dJWvb0fMWdwY3GiMYzpduRH+GQCqUVye+hhgXpFc1L3LpYaIFiSMemzF2XcWRXYRzKMBTCzEw2bqf5BY+4W/PdLV5RJ/DSw=
  on:
    tags: true
