language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - nightly
install:
  - pip install python-coveralls pytest-cov
  - pip install .
script:
  - cd tests
  - py.test . --cov vecrec
after_success:
  - coveralls

# vim: ts=2 sts=2 sw=2
